# Generated by Django 3.1.1 on 2020-10-29 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201029_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingrelation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 16, 3, 10, 671307)),
        ),
    ]
