# Generated by Django 3.1.1 on 2020-10-28 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_auto_20201028_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', through='tweets.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
